//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House_menegement.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_code { get; set; }
        public string month_and_year_of_payment { get; set; }
        public int view_Code { get; set; }
        public string payment_amount { get; set; }
        public string date_of_payment { get; set; }
        public int id_apartment { get; set; }
        public string Photo { get; set; }
        public string IsActual { get; set; }
        public string Management_Company { get; set; }
        public Nullable<int> buy_amount { get; set; }
        public Nullable<int> registration_time { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual payment_type payment_type { get; set; }
    }
}
